---
- name: Deploy GitLab
  ansible.builtin.import_playbook: gitlab.yml

- name: Deploy GitLab Runner
  ansible.builtin.import_playbook: gitlab-runner.yml

- name: Deploy Nexus Repository
  ansible.builtin.import_playbook: nexus.yml

- name: Deploy Aura MVP
  ansible.builtin.import_playbook: aura.yml

- name: Deploy Keycloak
  ansible.builtin.import_playbook: keycloak.yml

- name: Deploy Vault
  ansible.builtin.import_playbook: vault.yml
